import { Member } from './member.model';

export const MEMBER_MOCK: Member[] = [
  {
    id: '1',
    name: 'Emily Johnson',
    address: '123 Wellness Rd, Fitville',
    contactNumber: '555-0101',
    goal: 'Weight Loss',
    membershipStatus: 'Active',
  },
  {
    id: '2',
    name: 'Ben Miler',
    address: '456 Strength Ave, Muscleburg',
    contactNumber: '555-0102',
    goal: 'Muscle Gain',
    membershipStatus: 'Active',
  },
  {
    id: '3',
    name: 'Sophia Williams',
    address: '789 Cardio Ln, Endurance City',
    contactNumber: '555-0103',
    goal: 'Cardiovascular Health',
    membershipStatus: 'Expired',
  },
  {
    id: '4',
    name: 'Liam Brown',
    address: '101 Flex St, Agility Town',
    contactNumber: '555-0104',
    goal: 'Flexibility',
    membershipStatus: 'Active',
  },
  {
    id: '5',
    name: 'Olivia Jones',
    address: '212 Power Dr, Strengthford',
    contactNumber: '555-0105',
    goal: 'Strength Training',
    membershipStatus: 'Active',
  },
  {
    id: '6',
    name: 'Noah Garcia',
    address: '333 Speed Blvd, Velocityville',
    contactNumber: '555-0106',
    goal: 'Running',
    membershipStatus: 'Expired',
  },
  {
    id: '7',
    name: 'Ava Martinez',
    address: '444 Zen Way, Serenity Space',
    contactNumber: '555-0107',
    goal: 'Yoga',
    membershipStatus: 'Active',
  },
  {
    id: '8',
    name: 'Isabella Davis',
    address: '555 Balance Beam, Equilibrium Estates',
    contactNumber: '555-0108',
    goal: 'Gymnastics',
    membershipStatus: 'Active',
  },
  {
    id: '9',
    name: 'Mason Rodriguez',
    address: '666 Iron St, Hefty Heights',
    contactNumber: '555-0109',
    goal: 'Powerlifting',
    membershipStatus: 'Active',
  },
  {
    id: '10',
    name: 'Harper Wilson',
    address: '777 Swim Circle, Aqua Arbor',
    contactNumber: '555-0110',
    goal: 'Swimming',
    membershipStatus: 'Expired',
  },
  {
    id: '11',
    name: 'Ethan Moore',
    address: '888 Cycle Path, Pedalton',
    contactNumber: '555-0111',
    goal: 'Cycling',
    membershipStatus: 'Active',
  },
  {
    id: '12',
    name: 'Amelia Taylor',
    address: '999 Racket Road, Courtfield',
    contactNumber: '555-0112',
    goal: 'Tennis',
    membershipStatus: 'Active',
  },
  {
    id: '13',
    name: 'Alexander Anderson',
    address: '111 Hike Trail, Mountainview',
    contactNumber: '555-0113',
    goal: 'Hiking',
    membershipStatus: 'Active',
  },
  {
    id: '14',
    name: 'Mia Thomas',
    address: '222 Dance Floor, Rhythm City',
    contactNumber: '555-0114',
    goal: 'Dancing',
    membershipStatus: 'Expired',
  },
  {
    id: '15',
    name: 'James Jackson',
    address: '333 Martial Arts Way, Dojo District',
    contactNumber: '555-0115',
    goal: 'Karate',
    membershipStatus: 'Active',
  },
  {
    id: '16',
    name: 'Charlotte White',
    address: '444 Pilates Place, Core Creek',
    contactNumber: '555-0116',
    goal: 'Pilates',
    membershipStatus: 'Active',
  },
  {
    id: '17',
    name: 'Daniel Harris',
    address: '555 Rowers Row, Lakeview',
    contactNumber: '555-0117',
    goal: 'Rowing',
    membershipStatus: 'Active',
  },
  {
    id: '18',
    name: 'Evelyn Martin',
    address: '666 Climb Cliff, Summit Springs',
    contactNumber: '555-0118',
    goal: 'Rock Climbing',
    membershipStatus: 'Expired',
  },
  {
    id: '19',
    name: 'Joseph Thompson',
    address: '777 Boxing Ring, Knockout Kings',
    contactNumber: '555-0119',
    goal: 'Boxing',
    membershipStatus: 'Active',
  },
  {
    id: '20',
    name: 'Abigail Garcia',
    address: '888 Barre Studio, Ballet Burg',
    contactNumber: '555-0120',
    goal: 'Barre',
    membershipStatus: 'Active',
  },
  {
    id: '21',
    name: 'David Martinez',
    address: '999 Meditation Mount, Tranquil Top',
    contactNumber: '555-0121',
    goal: 'Meditation',
    membershipStatus: 'Active',
  },
  {
    id: '22',
    name: 'Avery Robinson',
    address: '121 Jump Street, Plyo Plaza',
    contactNumber: '555-0122',
    goal: 'Plyometrics',
    membershipStatus: 'Expired',
  },
  {
    id: '23',
    name: 'Sofia Clark',
    address: '232 Kickbox Corner, Combat City',
    contactNumber: '555-0123',
    goal: 'Kickboxing',
    membershipStatus: 'Active',
  },
  {
    id: '24',
    name: 'Logan Lewis',
    address: '343 Stretch Studio, Flexibility Fields',
    contactNumber: '555-0124',
    goal: 'Stretching',
    membershipStatus: 'Active',
  },
  {
    id: '25',
    name: 'Ella Lee',
    address: '454 Walker Way, Step City',
    contactNumber: '555-0125',
    goal: 'Walking',
    membershipStatus: 'Active',
  },
  {
    id: '26',
    name: 'Jackson Walker',
    address: '565 Crossfit Center, Intensity Isle',
    contactNumber: '555-0126',
    goal: 'Crossfit',
    membershipStatus: 'Expired',
  },
  {
    id: '27',
    name: 'Grace Hall',
    address: '676 HIIT Hill, Burn Borough',
    contactNumber: '555-0127',
    goal: 'HIIT',
    membershipStatus: 'Active',
  },
  {
    id: '28',
    name: 'Lucas Allen',
    address: '787 Tai Chi Terrace, Flowing Forest',
    contactNumber: '555-0128',
    goal: 'Tai Chi',
    membershipStatus: 'Active',
  },
  {
    id: '29',
    name: 'Chloe Young',
    address: '898 Zumba Zone, Dance District',
    contactNumber: '555-0129',
    goal: 'Zumba',
    membershipStatus: 'Active',
  },
  {
    id: '30',
    name: 'Samuel King',
    address: '1010 Powerlift Path, Maxout Meadows',
    contactNumber: '555-0130',
    goal: 'Olympic Lifting',
    membershipStatus: 'Expired',
  },
];
